// Vue/Prática/The Net Ninja/lesson-21/src/App.vue
<template>
  <div>
    <app-header></app-header>
    <app-heroes></app-heroes>
    <app-footer></app-footer>
  </div>
</template>

<script>
import Header from './components/Header.vue'
import Footer from './components/Footer.vue'
import Heroes from './components/Heroes.vue'

export default {
  components: {
    'app-header': Header,
    'app-footer': Footer,
    'app-heroes': Heroes
  },
  data () {
    return {

    }
  }
}
</script>

<style>

</style>

// Projetos/React/react-todo-app/src/App.js
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import AddTask from './components/AddTask';
import Footer from './components/Footer';
import Header from './components/Header';
import TaskList from './components/TaskList';

function App() {
  return (
    <Router>
      <div className="App">
        <Header />
          <Switch>
            <Route exact path="/">
              <TaskList />
            </Route>
            <Route path="/add">
              <AddTask />
            </Route>
          </Switch>
        <Footer />
      </div>
    </Router>
  );
}

export default App;
