// Courses/React/The Net Ninja/Skeleton Screens/src/App.js
import Articles from "./components/Articles";
import User from "./components/User";

function App() {
  return (
    <div className="App">
      <header>
        <h1>React Skeletons</h1>
      </header>
      <div className="content">
        <Articles />
        <User />
      </div>
    </div>
  );
}

export default App;

// Vue/Prática/The Net Ninja/lesson-21/src/App.vue
<template>
  <div>
    <app-header></app-header>
    <app-heroes></app-heroes>
    <app-footer></app-footer>
  </div>
</template>

<script>
import Header from './components/Header.vue'
import Footer from './components/Footer.vue'
import Heroes from './components/Heroes.vue'

export default {
  components: {
    'app-header': Header,
    'app-footer': Footer,
    'app-heroes': Heroes
  },
  data () {
    return {

    }
  }
}
</script>

<style>

</style>
